config/routes.rb
Rails.application.routes.draw do

  unauthenticated :user do
    root :to => 'home#index', :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  end
  root :to => 'fire_department#index', :constraints => lambda { |request| request.env['warden'].user.role == 'fire_safety_officer' if request.env['warden'].user }, as: :fire_department_root
   root :to => 'treasury_department#index', :constraints => lambda { |request| request.env['warden'].user.role == 'collection_officer' if request.env['warden'].user }, as: :treasury_department_root
resources :search_results, only: [:index]
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bplo_officer' if request.env['warden'].user }, as: :bplo_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'engineering_officer' if request.env['warden'].user }, as: :engineering_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'zoning_officer' if request.env['warden'].user }, as: :zoning_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'system_administrator' if request.env['warden'].user }, as: :admin_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'mayors_office_staff' if request.env['warden'].user }, as: :mayor_department_root

  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: "bplo_section/settings/users"}
  resources :users, only: [:show, :edit, :update]
  resources :reports, only: [:index]
  namespace :reports do
    resources :bir, only: [:index]
    resources :gcf, only: [:index]
    resources :dilg, only: [:index]
    resources :cmci, only: [:index]
    resources :dti, only: [:index]
    resources :bfp, only: [:index]
    resources :philhealth, only: [:index]
    resources :sss, only: [:index]
  end

  resources :competetive_index_categories, only: [:show]
  resources :collections, only: [:index, :show, :destroy]
  resources :business_requirement_verifications, only: [:create]
  resources :business_permits, only: [:index, :show]
  resources :business_activities, only: [:destroy], module: :businesses
  resources :business_fees, only: [:destroy], module: :businesses
  resources :dashboard, only: [:index]
  resources :taxpayers do
    resources :taxpayer_businesses, only: [:new, :create], module: :taxpayers
  end
  resources :businesses, only: [:index, :show, :destroy] do
    resources :info, only: [:index], module: :businesses
    resources :checklist, only: [:index], module: :businesses
    resources :settings, only: [:index], module: :businesses
    resources :business_permits, only: [:index], module: :businesses
    resources :bir_registrations, only: [:new, :create], module: :businesses
    resources :dti_registrations, only: [:new, :create], module: :businesses
    resources :sec_registrations, only: [:new, :create], module: :businesses
    resources :cda_registrations, only: [:new, :create], module: :businesses

    resources :business_tax_payments, only: [:new, :create], module: :businesses
    resources :payments, only: [:new, :create], module: :businesses

    resources :assessments, only: [:index, :new, :create], module: :businesses
    resources :additional_assessments, only: [:new, :create], module: :businesses
    resources :revocations, only: [:new, :create], module: :businesses
    resources :late_registration_interests, only: [:create], module: :businesses
    resources :fire_safety_inspection_fee_collections, only: [:new, :create], module: :businesses

  end
  resources :departments, only: [:index, :new, :create]
  resources :business_registrations, only: [:new, :create]
  resources :business_permit_applications, shallow: true do
    resources :permit_approvals, only: [:new, :create]
  end

  namespace :bplo_section do
    resources :line_of_businesses, only: [:show]
    resources :taxpayers, only: [:show] do
      resources :businesses, only: [:new, :create]
      resources :tricycles, only: [:new, :create]
    end

    resources :businesses, only: [:show, :edit, :update] do
      resources :line_of_business_selections, only: [:new, :create], module: :businesses
      resources :business_permit_applications, only: [:new, :create], module: :businesses
      resources :business_activities, only: [:index, :new, :create]
      resources :cockpit_details, only: [:index, :new, :create]
      resources :gross_sales, only: [:new, :create, :edit, :update], module: :businesses
      resources :business_requirements, only: [:new, :create]
      resources :business_fees, only: [:new, :create]
      resources :gross_sales_tax_configs, only: [:edit, :update], module: :configurations
      resources :building_permit_fees, only: [:new, :create], module: :businesses
      resources :electrical_installation_fees, only: [:new, :create], module: :businesses
      resources :plumbing_installation_fees, only: [:new, :create], module: :businesses
      resources :other_accessories_fees, only: [:new, :create], module: :businesses
      resources :engineering_penalties, only: [:new, :create], module: :businesses
      resources :surcharges, only: [:new, :create], module: :businesses
      resources :late_registration_interests, only: [:new, :create], module: :businesses


      resources :zoning_fees, only: [:new, :create], module: :businesses
      resources :annual_inspection_fees, only: [:new, :create], module: :businesses
      resources :occupancy_permit_fees, only: [:new, :create], module: :businesses
      resources :documentary_stamp_fees, only: [:new, :create, :edit], module: :businesses
      resources :sealing_fees, only: [:new, :create], module: :businesses
      resources :stalls, only: [:new, :create], module: :businesses

    end
    resources :business_activities, only: [:show] do
      resources :gross_sales, only: [:new, :create]
    end



    resources :gross_sales_tax_business_categories, only: [:show] do
      resources :gross_sales_taxes, only: [:new, :create], module: :taxes
    end
    resources :business_requirements, only: [:destroy]


    namespace :configs do
      resources :fire_safety_inspection_fee_configs, only: [:new, :create]
    end

    namespace :taxes do
      resources :capital_taxes, only: [:new, :create]
    end
    resources :settings, only: [:index]
    namespace :settings do
      resources :public_markets, only: [:new, :create]
      resources :ownership_types, only: [:new, :create, :edit, :update]
      resources :mode_of_payments, only: [:new, :create, :edit, :update]
      resources :barangays, only: [:new, :create, :edit, :update]
      resources :line_of_businesses, only: [:index, :new, :create, :edit, :update, :show]
      resources :fees, only: [:new, :create, :edit, :update]
      resources :taxes, only: [:new, :create, :edit, :update]
      resources :cockpit_personnel_fees, only: [:new, :create, :edit, :update]

      resources :late_payment_surcharges, only: [:new, :create]
      resources :interest_rates, only: [:new, :create]
      resources :required_documents, only: [:new, :create, :edit, :update]
      resources :departments, only: [:new, :create]
      resources :gross_sales_tax_business_categories, only: [:new, :create]
      resources :users, only: [:new, :create, :show]
      resources :signatories, only: [:new, :create]
      resources :permit_application_date_ranges, only: [:new, :create]
      resources :tricycle_fees, only: [:new, :create, :edit, :update]
      resources :tricycle_requirements, only: [:new, :create, :edit, :update]
      resources :tricycle_organizations, only: [:new, :create, :edit, :update]
    end
  end
  resources :business_requirements, shallow: true do
    resources :verifications, only: [:new, :create], module: [:businesses, :business_requirements]
    resources :issuances, only: [:new, :create], module: [:businesses, :business_requirements]
  end
  namespace :fees_settings do
    resources :sanitary_inspection_fees, only: [:new, :create]
    resources :storage_permit_fees, only: [:new, :create]
  end
  resources :monitoring, only: [:index]
  namespace :monitoring do
    resources :closed_businesses, only: [:index]

    resources :unrenewed_businesses, only: [:index]
    resources :barangays, only: [:show] do
      match "/registered_businesses" => "registered_businesses#index",  via: [:get], on: :collection
      match "/unrenewed_businesses" => "unrenewed_businesses#index",  via: [:get], on: :collection
    end
  end
  resources :bir_registrations, only: [:edit, :update], module: :registrations
  resources :dti_registrations, only: [:edit, :update], module: :registrations
  resources :sec_registrations, only: [:edit, :update], module: :registrations
  resources :cda_registrations, only: [:edit, :update], module: :registrations
  namespace :public_markets do
    resources :transient_tenants, only: [:index]
    resources :regular_tenants, only: [:index]
  end
  resources :tricycles do
    resources :applicable_tricycle_fees, only: [:new, :create], module: :tricycles
    resources :fare_adjustment_fees, only: [:new, :create], module: :tricycles
    resources :late_registration_interests, only: [:new, :create], module: :tricycles
    resources :surcharges, only: [:new, :create], module: :tricycles
    resources :tricycle_requirements, only: [:new, :create]
    resources :assessments, only: [:new, :create], module: :tricycles
    resources :payments, only: [:new, :create], module: :tricycles
    resources :tricycle_permit_applications, only: [:new, :create], module: :tricycles
  end

  resources :applicable_tricycle_fees, only: [:destroy], module: :tricycles
  resources :tricycle_registrations, only: [:new, :create]
  resources :tricycle_permit_applications, shallow: true do

app/models/tricycles/tricycle_permit_condition.rb
module Tricycles
  class TricyclePermitCondition < ApplicationRecord
    belongs_to :tricycle_permit_approval
    belongs_to :permit_condition
  end
end

app/controllers/assessments/payments_controller.rb
module Assessments
  class PaymentsController < ApplicationController
    def new
      @assessment = Accounting::Entry.find(params[:assessment_id])
      @entry = Accounting::Entry.new
      @entry.credit_amounts.build
      @entry.debit_amounts.build
    end
    def create
      @assessment = Accounting::Entry.find(params[:assessment_id])
      @entry = Accounting::Entry.create(entry_params)
      @entry.commercial_document = @assessment.commercial_document
      @entry.recorder = current_user
      @entry.transaction_type = 'payment'
      @entry.barangay = @assessment.commercial_document.barangay
      @entry.description = "Payment of fees and taxes"
      if @entry.save!
        redirect_to business_path(@assessment.commercial_document), notice: 'Payment saved successfully.'
          @assessment.paid!
      else
        render :new
      end
    end

    private def entry_params
      params.require(:accounting_entry).permit(:reference_number, :description, :entry_date, credit_amounts_attributes: [:amount, :account_id, :id, :commercial_document_id, :commercial_document_type], debit_amounts_attributes: [:amount, :account_id, :id, :commercial_document_type, :commercial_document_id] )
    end
  end
  end

app/controllers/bplo_section/tricycles_controller.rb
module BploSection
  class TricyclesController < ApplicationController
    def new
      @taxpayer = Taxpayer.friendly.find(params[:taxpayer_id])
      @tricycle = @taxpayer.tricycles.build
      @tricycle.addresses.build
      @tricycle.tricycle_permit_applications.build
      authorize @tricycle
    end

    def create
      @taxpayer = Taxpayer.friendly.find(params[:taxpayer_id])
      @tricycle = @taxpayer.tricycles.create(tricycle_params)
      authorize @tricycle
      if @tricycle.valid?
        @tricycle.save
          Tricycles::ApplicableTricycleFee.set_default_fees(@tricycle)
          Tricycles::ApplicableTricycleFee.set_additional_fees(@tricycle)
          Tricycles::ApplicableTricycleRequirement.set_default_requirements(@tricycle)
        redirect_to @tricycle, notice: "Tricycle Information saved successfully."
      else
        render :new
      end
    end

    private
    def tricycle_params
      params.require(:tricycle).permit(:mtop_number, :plate_number,
      addresses_attributes: [:barangay_id, :municipality_or_city_id, :province_id],
      tricycle_permit_applications_attributes: [:transaction_type, :application_date, :application_number])
    end
  end
end

app/controllers/businesses/payments_controller.rb
module Businesses
  class PaymentsController < ApplicationController
    def new
      @business = Business.friendly.find(params[:business_id])
      @entry = Accounting::Entry.new
      @entry.credit_amounts.build
      @entry.debit_amounts.build
    end
    def create
      @business = Business.friendly.find(params[:business_id])
      @entry = Accounting::Entry.create(entry_params)
      @entry.commercial_document = @business
      @entry.recorder = current_user
      @entry.transaction_type = 'payment'
      @entry.barangay = @business.barangay
      if @entry.save
        redirect_to @business, notice: 'Payment saved successfully.'
      else
        render :new
      end
    end

    private def entry_params
      params.require(:accounting_entry).permit(:reference_number, :description, :entry_date, credit_amounts_attributes: [:amount, :account_id, :id], debit_amounts_attributes: [:amount, :account_id, :id] )
    end
  end
end

app/controllers/special_permits/payments_controller.rb
module SpecialPermits
  class PaymentsController < ApplicationController
    def new
      @special_permit = TaxpayerSpecialPermit.find(params[:special_permit_id])
      @payment = Accounting::Entry.new
      @payment.credit_amounts.build
      @payment.debit_amounts.build

    end
    def create
      @special_permit = TaxpayerSpecialPermit.find(params[:special_permit_id])
      @payment = Accounting::Entry.create(entry_params)
      @payment.commercial_document = @special_permit
      @payment.recorder = current_user
      @payment.transaction_type = 'payment'
      @payment.barangay = @special_permit.taxpayer.barangay
      if @payment.save
        redirect_to special_permit_url(@special_permit), notice: 'Assessment saved successfully.'
        @payment.create_activity key: 'entry.created_at', owner: current_user
      else
        render :new
      end
    end

    private def entry_params
      params.require(:accounting_entry).permit(:reference_number, :description, :entry_date, credit_amounts_attributes: [:amount, :account_id, :id], debit_amounts_attributes: [:amount, :account_id, :id] )
    end
  end
  end

app/controllers/treasury_department/assessments/payments_controller.rb
module TreasuryDepartment
  module Assessments
    class PaymentsController < ApplicationController
      def new
        @assessment = Accounting::Entry.find(params[:assessment_id])
        @entry = Accounting::Entry.new
        @entry.credit_amounts.build
        @entry.debit_amounts.build
      end
      def create
        @assessment = Accounting::Entry.find(params[:assessment_id])
        @entry = Accounting::Entry.create(entry_params)
        @entry.commercial_document = @assessment.commercial_document
        @entry.recorder = current_user
        @entry.transaction_type = 'payment'
        @entry.barangay = @assessment.commercial_document.barangay
        @entry.description = "Payment of fees and taxes"
        if @entry.save!
          redirect_to treasury_department_business_path(@assessment.commercial_document), notice: 'Payment saved successfully.'
            @assessment.paid!
        else
          render :new
        end
      end

      private def entry_params
        params.require(:accounting_entry).permit(:reference_number, :description, :entry_date, credit_amounts_attributes: [:amount, :account_id, :id], debit_amounts_attributes: [:amount, :account_id, :id] )
      end
    end
    end
end

app/controllers/tricycles/applicable_tricycle_fees_controller.rb
module Tricycles
  class ApplicableTricycleFeesController < ApplicationController
    def new
      @tricycle = Tricycle.find(params[:tricycle_id])
      @fee = @tricycle.applicable_tricycle_fees.build
      authorize @fee
    end
    def create
      @tricycle = Tricycle.find(params[:tricycle_id])
      @fee = @tricycle.applicable_tricycle_fees.create(fee_params)
      authorize @fee
      @fee.save
      redirect_to new_tricycle_applicable_tricycle_fee_path(@tricycle), notice: "Fee added successfully."
    end
    def destroy
      @fee = Tricycles::ApplicableTricycleFee.find(params[:id])
      authorize @fee
      @fee.destroy
      redirect_to @fee.tricycle, alert: "Fee removed successfully."
    end

    private
    def fee_params
      params.require(:tricycles_applicable_tricycle_fee).permit(:tricycle_fee_id)
    end
  end
end

app/controllers/tricycles/fare_adjustment_fees_controller.rb
module Tricycles
  class FareAdjustmentFeesController < ApplicationController
    def new
      @tricycle = Tricycle.find(params[:tricycle_id])
      @fee = @tricycle.fare_adjustment_fees.build
    end
    def create
      @tricycle = Tricycle.find(params[:tricycle_id])
      @fee = @tricycle.fare_adjustment_fees.create(fee_params)
      if @fee.save
        redirect_to @tricycle, notice: "Fare Adjustment Fee saved successfully."
      else
        render :new
      end
    end

    private
    def fee_params
      params.require(:fees_fare_adjustment_fee).permit(:calendar_year, :amount)
    end
  end
end 

app/views/tricycles/payments/new.html.erb
<% breadcrumb :new_tricycle_assessment, @tricycle %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <!-- Widget: user widget style 1 -->
  <div class="box box-widget widget-user-2">
    <!-- Add the bg color to the header using any of the bg-* classes -->
    <div class="widget-user-header">
      <div class="widget-user-image">
        <%=image_tag(@tricycle.taxpayer.avatar.url(:large), class: "img-circle") %>
      </div>
      <!-- /.widget-user-image -->
      <h3 class="widget-user-username">
        <%=link_to tricycle_path(@tricycle) do %>
          <%= @tricycle.name.try(:upcase) %></h3>
          <h5 class="widget-user-desc text-muted"><%= @tricycle.taxpayer_full_name %></h5>
        <% end %>
    </div>
    <div class="box-body">

      <br>
            <div class="row">
              <div class="col-md-8">
                <h4> Fees </h4>
              </div>
            </div>
            <br>
            <small class="text-muted">&nbsp; &nbsp; FEES </small><p></p>

            <% @tricycle.tricycle_fees.each do |fee| %>
              <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-7">
                  <%= fee.name %>
                </div>
                <div class="col-md-3">
                  <span class="pull-right"><%=number_to_currency fee.amount %></span>
                </div>
              </div>
              <br>
            <% end %>
            <div class="row">
              <div class="col-md-1">
              </div>
              <div class="col-md-8">
                Fare Adjustment Fee
              </div>
              <div class="col-md-2">
                  <span class="pull-right"><%=number_to_currency @tricycle.fare_adjustment_fees.for_current_year %></span>
              </div>
            </div>
            <br>
          <small class="text-danger">&nbsp; &nbsp; SURCHARGES </small><p></p>
          <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-8">
              Surcharges <br>
            </div>
            <div class="col-md-2">
              <span class="pull-right"><%=number_to_currency @tricycle.surcharges.for_current_year %></span>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-8">
              Interests <br>
            </div>
            <div class="col-md-2">
              <%if @tricycle.late_registration_interests.for_current_year.zero? && policy([:tricycles, :surcharge]).create?  && @tricycle.late_registration? %>
                <%=link_to tricycle_surcharges_path(@tricycle), title: 'Assess Surchages', method: :create do %>
                  <span class="btn btn-primary btn-xs" title="Assess Surcharges" data-toggle="tooltip"><i class="fa fa-plus"></i> Assess </span>
                <% end %>
                <% else %>
                  <span class="pull-right"><%=number_to_currency @tricycle.late_registration_interests.for_current_year %></span>
              <% end %>
            </div>
          </div>
          <hr>
            <div class="row">
              <div class="col-md-1">
              </div>
              <div class="col-md-7">
                <b>TOTAL</b>
              </div>
              <div class="col-md-3">
                <span class="pull-right"><b><%=number_to_currency @tricycle.total_fees %></b></span>
              </div>
            </div>
          <hr>

              <%= simple_form_for @entry, url: :tricycle_payments do |f| %>
                <%= f.error_notification %>
                <!-- tricycle Fees -->
                <% if @tricycle.tricycle_fees.present? %>
                  <% @tricycle.tricycle_fees.each do |fee| %>
                    <%=f.simple_fields_for :debit_amounts do |d|  %>
                      <%= d.input :amount, input_html: {autocomplete: "off", class: "input-lg", value: fee.amount },  as: :hidden %>
                      <%= d.input :account_id, input_html: {value:  Accounting::Account.find_by_name("Cash - Local Treasury").id },  as: :hidden %>
                    <% end %>
                    <%=f.simple_fields_for :credit_amounts do |c|  %>
                      <%= c.input :amount, input_html: {autocomplete: "off", class: "input-lg", value: fee.amount },  as: :hidden %>
                      <%= c.input :account_id, input_html: { value: fee.debit_account_id}, as: :hidden %>
                    <% end %>
                  <% end %>
                <% end %>
                <!-- Surcharges -->
                <% if @tricycle.surcharges.for_current_year.present? && @tricycle.surcharges.for_current_year > 0 %>
                  <%=f.simple_fields_for :debit_amounts do |d|  %>
                    <%=d.input :amount, input_html: {autocomplete: "off", class: "input-lg", value: @tricycle.surcharges.for_current_year }, as: :hidden  %>
                    <%=d.input :account_id, input_html: {value:  Accounting::Account.find_by_name("Cash - Local Treasury").id },  as: :hidden %>
                  <% end %>
                  <%=f.simple_fields_for :credit_amounts do |c|  %>
                    <%=c.input :amount, input_html: {autocomplete: "off", class: "input-lg", value: @tricycle.surcharges.for_current_year}, as: :hidden  %>
                    <%=c.input :account_id, input_html: { value: Businesses::Surcharge.new.debit_account.id }, as: :hidden  %>
                  <% end %>
                <% end %>
                <!-- Interests -->
                <% if @tricycle.late_registration_interests.for_current_year.present? && @tricycle.late_registration_interests.for_current_year > 0 %>
                  <%=f.simple_fields_for :debit_amounts do |d|  %>
                    <%=d.input :amount, input_html: {autocomplete: "off", class: "input-lg", value: @tricycle.late_registration_interests.for_current_year }, as: :hidden  %>
                    <%=d.input :account_id, input_html: {value:  Accounting::Account.find_by_name("Cash - Local Treasury").id },  as: :hidden %>
                  <% end %>
                  <%=f.simple_fields_for :credit_amounts do |c|  %>
                    <%=c.input :amount, input_html: {autocomplete: "off", class: "input-lg", value: @tricycle.late_registration_interests.for_current_year}, as: :hidden  %>
                    <%=c.input :account_id, input_html: { value: Businesses::LateRegistrationInterest.new.debit_account.id }, as: :hidden  %>
                  <% end %>
                <% end %>
                  <!-- Fare Adjustment Fee-->
                  <% if !@tricycle.fare_adjustment_fees.for_current_year.zero? %>
                    <%=f.simple_fields_for :debit_amounts do |d|  %>
                      <%=d.input :amount, input_html: {autocomplete: "off", class: "input-lg", value: @tricycle.fare_adjustment_fees.for_current_year }, as: :hidden  %>
                      <%=d.input :account_id, input_html: {value:  Accounting::Account.find_by_name("Cash - Local Treasury").id },  as: :hidden %>
                    <% end %>
                    <%=f.simple_fields_for :credit_amounts do |c|  %>
                      <%=c.input :amount, input_html: {autocomplete: "off", class: "input-lg", value: @tricycle.fare_adjustment_fees.for_current_year }, as: :hidden  %>
                      <%=c.input :account_id, input_html: {value: Fees::FareAdjustmentFee.new.debit_account.id}, as: :hidden %>
                    <% end %>
                  <% end %>

                  <%= f.input :reference_number, required: true, label: "OR Number" %>
                  <%= f.input :entry_date, label: "Payment Date", as: :string, input_html: { class: "datepicker", default: Date.today } %>
                  <%= f.input :description, input_html: { value: "Payment of fees, surcharges and interests" }, as: :hidden %>
                  <div class="box-footer">
                    <%= f.submit "Save Payment", class: "btn btn-primary btn-flat pull-right", data: { disable_with: "Saving Payment..."} %>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>