config/routes.rb
Rails.application.routes.draw do

  unauthenticated :user do
    root :to => 'home#index', :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  end
  root :to => 'fire_department#index', :constraints => lambda { |request| request.env['warden'].user.role == 'fire_safety_officer' if request.env['warden'].user }, as: :fire_department_root
   root :to => 'treasury_department#index', :constraints => lambda { |request| request.env['warden'].user.role == 'collection_officer' if request.env['warden'].user }, as: :treasury_department_root
resources :search_results, only: [:index]
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bplo_officer' if request.env['warden'].user }, as: :bplo_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'engineering_officer' if request.env['warden'].user }, as: :engineering_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'zoning_officer' if request.env['warden'].user }, as: :zoning_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'system_administrator' if request.env['warden'].user }, as: :admin_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'mayors_office_staff' if request.env['warden'].user }, as: :mayor_department_root

  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: "bplo_section/settings/users"}
  resources :users, only: [:show, :edit, :update]
  resources :reports, only: [:index]
  namespace :reports do
    resources :bir, only: [:index]
    resources :gcf, only: [:index]
    resources :dilg, only: [:index]
    resources :cmci, only: [:index]
    resources :dti, only: [:index]
    resources :bfp, only: [:index]
    resources :philhealth, only: [:index]
    resources :sss, only: [:index]
  end

  resources :competetive_index_categories, only: [:show]
  resources :collections, only: [:index, :show, :destroy]
  resources :business_requirement_verifications, only: [:create]
  resources :business_permits, only: [:index, :show]
  resources :business_activities, only: [:destroy], module: :businesses
  resources :business_fees, only: [:destroy], module: :businesses
  resources :dashboard, only: [:index]
  resources :taxpayers do
    resources :taxpayer_businesses, only: [:new, :create], module: :taxpayers
  end
  resources :businesses, only: [:index, :show, :destroy] do
    resources :info, only: [:index], module: :businesses
    resources :checklist, only: [:index], module: :businesses
    resources :settings, only: [:index], module: :businesses
    resources :business_permits, only: [:index], module: :businesses
    resources :bir_registrations, only: [:new, :create], module: :businesses
    resources :dti_registrations, only: [:new, :create], module: :businesses
    resources :sec_registrations, only: [:new, :create], module: :businesses
    resources :cda_registrations, only: [:new, :create], module: :businesses

    resources :business_tax_payments, only: [:new, :create], module: :businesses
    resources :payments, only: [:new, :create], module: :businesses

    resources :assessments, only: [:index, :new, :create], module: :businesses
    resources :additional_assessments, only: [:new, :create], module: :businesses
    resources :revocations, only: [:new, :create], module: :businesses
    resources :late_registration_interests, only: [:create], module: :businesses
    resources :fire_safety_inspection_fee_collections, only: [:new, :create], module: :businesses

  end
  resources :departments, only: [:index, :new, :create]
  resources :business_registrations, only: [:new, :create]
  resources :business_permit_applications, shallow: true do
    resources :permit_approvals, only: [:new, :create]
  end

  namespace :bplo_section do
    resources :line_of_businesses, only: [:show]
    resources :taxpayers, only: [:show] do
      resources :businesses, only: [:new, :create]
      resources :tricycles, only: [:new, :create]
    end

    resources :businesses, only: [:show, :edit, :update] do
      resources :line_of_business_selections, only: [:new, :create], module: :businesses
      resources :business_permit_applications, only: [:new, :create], module: :businesses
      resources :business_activities, only: [:index, :new, :create]
      resources :cockpit_details, only: [:index, :new, :create]
      resources :gross_sales, only: [:new, :create, :edit, :update], module: :businesses
      resources :business_requirements, only: [:new, :create]
      resources :business_fees, only: [:new, :create]
      resources :gross_sales_tax_configs, only: [:edit, :update], module: :configurations
      resources :building_permit_fees, only: [:new, :create], module: :businesses
      resources :electrical_installation_fees, only: [:new, :create], module: :businesses
      resources :plumbing_installation_fees, only: [:new, :create], module: :businesses
      resources :other_accessories_fees, only: [:new, :create], module: :businesses
      resources :engineering_penalties, only: [:new, :create], module: :businesses
      resources :surcharges, only: [:new, :create], module: :businesses
      resources :late_registration_interests, only: [:new, :create], module: :businesses


      resources :zoning_fees, only: [:new, :create], module: :businesses
      resources :annual_inspection_fees, only: [:new, :create], module: :businesses
      resources :occupancy_permit_fees, only: [:new, :create], module: :businesses
      resources :documentary_stamp_fees, only: [:new, :create, :edit], module: :businesses
      resources :sealing_fees, only: [:new, :create], module: :businesses
      resources :stalls, only: [:new, :create], module: :businesses

    end
    resources :business_activities, only: [:show] do
      resources :gross_sales, only: [:new, :create]
    end



    resources :gross_sales_tax_business_categories, only: [:show] do
      resources :gross_sales_taxes, only: [:new, :create], module: :taxes
    end
    resources :business_requirements, only: [:destroy]


    namespace :configs do
      resources :fire_safety_inspection_fee_configs, only: [:new, :create]
    end

    namespace :taxes do
      resources :capital_taxes, only: [:new, :create]
    end
    resources :settings, only: [:index]
    namespace :settings do
      resources :public_markets, only: [:new, :create]
      resources :ownership_types, only: [:new, :create, :edit, :update]
      resources :mode_of_payments, only: [:new, :create, :edit, :update]
      resources :barangays, only: [:new, :create, :edit, :update]
      resources :line_of_businesses, only: [:index, :new, :create, :edit, :update, :show]
      resources :fees, only: [:new, :create, :edit, :update]
      resources :taxes, only: [:new, :create, :edit, :update]
      resources :cockpit_personnel_fees, only: [:new, :create, :edit, :update]

      resources :late_payment_surcharges, only: [:new, :create]
      resources :interest_rates, only: [:new, :create]
      resources :required_documents, only: [:new, :create, :edit, :update]
      resources :departments, only: [:new, :create]
      resources :gross_sales_tax_business_categories, only: [:new, :create]
      resources :users, only: [:new, :create, :show]
      resources :signatories, only: [:new, :create]
      resources :permit_application_date_ranges, only: [:new, :create]
      resources :tricycle_fees, only: [:new, :create, :edit, :update]
      resources :tricycle_requirements, only: [:new, :create, :edit, :update]
      resources :tricycle_organizations, only: [:new, :create, :edit, :update]
    end
  end
  resources :business_requirements, shallow: true do
    resources :verifications, only: [:new, :create], module: [:businesses, :business_requirements]
    resources :issuances, only: [:new, :create], module: [:businesses, :business_requirements]
  end
  namespace :fees_settings do
    resources :sanitary_inspection_fees, only: [:new, :create]
    resources :storage_permit_fees, only: [:new, :create]
  end
  resources :monitoring, only: [:index]
  namespace :monitoring do
    resources :closed_businesses, only: [:index]

    resources :unrenewed_businesses, only: [:index]
    resources :barangays, only: [:show] do
      match "/registered_businesses" => "registered_businesses#index",  via: [:get], on: :collection
      match "/unrenewed_businesses" => "unrenewed_businesses#index",  via: [:get], on: :collection
    end
  end
  resources :bir_registrations, only: [:edit, :update], module: :registrations
  resources :dti_registrations, only: [:edit, :update], module: :registrations
  resources :sec_registrations, only: [:edit, :update], module: :registrations
  resources :cda_registrations, only: [:edit, :update], module: :registrations
  namespace :public_markets do
    resources :transient_tenants, only: [:index]
    resources :regular_tenants, only: [:index]
  end
  resources :tricycles do
    resources :applicable_tricycle_fees, only: [:new, :create], module: :tricycles
    resources :fare_adjustment_fees, only: [:new, :create], module: :tricycles
    resources :late_registration_interests, only: [:new, :create], module: :tricycles
    resources :surcharges, only: [:new, :create], module: :tricycles
    resources :tricycle_requirements, only: [:new, :create]
    resources :assessments, only: [:new, :create], module: :tricycles
    resources :payments, only: [:new, :create], module: :tricycles
    resources :tricycle_permit_applications, only: [:new, :create], module: :tricycles
  end

  resources :applicable_tricycle_fees, only: [:destroy], module: :tricycles
  resources :tricycle_registrations, only: [:new, :create]
  resources :tricycle_permit_applications, shallow: true do

app/models/businesses/bir_registration.rb
module Businesses
  class BirRegistration < ApplicationRecord
    belongs_to :business
    validates :registration_number, presence: true, uniqueness: true
    validates :date_issued, :expiry_date, presence: true

    def expired?
      expiry_date < Time.zone.now
    end
  end
end

app/models/businesses/business_activity.rb
module Businesses
  class BusinessActivity < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    belongs_to :business

    belongs_to :line_of_business, class_name: "BploSection::Settings::LineOfBusiness"
    belongs_to :storage_permit_fee, class_name: "Fees::StoragePermitFee"

    has_many :gross_sales, class_name: "Businesses::GrossSale"
    delegate :name, to: :line_of_business
    delegate :mayors_permit_fee_amount, to: :line_of_business
    delegate :amount, to: :storage_permit_fee, prefix: true, allow_nil: true
    before_commit :set_storage_permit_fee, :set_business_requirements
    def self.total_fees 
      all.sum(&:total_fees)
    end
    def self.with_storage_permit_fees
      all.select{|a| a.storage_permit_fee.present?}
    end
    def total_fees
      mayors_permit_fee_amount * number_of_unit
    end

    def set_storage_permit_fee
      if line_of_business.has_storage_permit_fee?
        Fees::StoragePermitFee.set(self)
      end
    end
    def set_business_requirements
      BploSection::Settings::RequiredDocument.set_additional_requirements(self.business)
    end
  end
end

app/models/businesses/business_area.rb
module Businesses
  class BusinessArea < ApplicationRecord
    belongs_to :business
    belongs_to :sanitary_inspection_fee, class_name: "Fees::SanitaryInspectionFee"

    validates :area, presence: true, numericality: true
    after_save :set_sanitary_inspection_fee
    def fee
      if sanitary_inspection_fee
        sanitary_inspection_fee.amount
      else
        Fees::SanitaryInspectionFee.order(created_at: :asc).first.try(:amount)
      end
    end
    
    private
    def set_sanitary_inspection_fee
      Fees::SanitaryInspectionFee.set(self)
    end

  end
end

app/models/businesses/business_capital.rb
module Businesses
  class BusinessCapital < ApplicationRecord
    belongs_to :business
    validates :amount, presence: true, numericality: true
  end
end

app/models/businesses/business_fee.rb
module Businesses
  class BusinessFee < ApplicationRecord
    has_paper_trail
    belongs_to :business
    belongs_to :fee

    # validates :fee_id, uniqueness: { scope: :business_id }
    delegate :name, :amount, :default_fee?,  to: :fee, allow_nil: true
    delegate :assessed_for_current_year?, to: :business
  end
end

app/models/businesses/business_permits/business_permit_application.rb
module Businesses
  module BusinessPermits
    class BusinessPermitApplication < ApplicationRecord
      enum transaction_type: [:new_application, :renew]
      belongs_to :business
      has_one :business_permit_approval, class_name: "Businesses::BusinessPermits::BusinessPermitApproval", dependent: :destroy

      validates :application_number, presence: true, uniqueness: true
      validates :application_date, presence: true


      def self.for_current_year
        all.select {|a| a.application_date.between?(Time.zone.now.beginning_of_year, Time.zone.now.end_of_year)}
      end

      def approved?
        business_permit_approval.present?
      end
      def expired?
        business_permit_approval.date_approved > Time.zone.now.tomorrow
      end
    end
  end
end

app/models/businesses/business_permits/business_permit_approval.rb
module Businesses
  module BusinessPermits
    class BusinessPermitApproval < ApplicationRecord
      include PgSearch
      multisearchable :against => [:permit_number]
      has_one :business_tin_plate, class_name: "Businesses::BusinessTinPlate", dependent: :destroy
      belongs_to :approver, class_name: "User", foreign_key: 'approver_id'
      belongs_to :business_permit_application, class_name: "Businesses::BusinessPermits::BusinessPermitApplication"
      has_many :conditions, dependent: :destroy, class_name: "BusinessPermitCondition"
      has_many :permit_conditions, through: :conditions
      delegate :business, to: :business_permit_application, allow_nil: true
      delegate :name, :ownership_type_name, :full_address, :taxpayers_full_name, to: :business, prefix: true, allow_nil: true
      delegate :taxpayers_full_name, to: :business, prefix: true, allow_nil: true
      delegate :transaction_type, :expired?, to: :business_permit_application, allow_nil: true

      validates :permit_number, presence: true, uniqueness: true
      after_save :set_default_conditions
      after_commit :set_business_status, :set_business_tin_plate, if: :persisted?
      accepts_nested_attributes_for :business_tin_plate
      #for reporting purposes
      def self.date_approved(business)
      end
      def self.for_current_year
        all.select {|a| a.date_approved.between?(Time.zone.now.beginning_of_year, Time.zone.now.end_of_year)}
      end
      def name
        business.name
      end

      private
      def set_business_status
        if self.business_permit_application.new_application?
          business.new_business!
        elsif self.business_permit_application.renew?
          business.renewed!
        end
      end
      def set_default_conditions
        PermitCondition.set_default(self)
      end
      def set_business_tin_plate
        self.business.business_tin_plate = self.business_tin_plate
      end
    end
  end
end

app/models/businesses/business_permits/revocation.rb
module Businesses
  module BusinessPermits
    class Revocation < ApplicationRecord
      belongs_to :business
      validates :remarks, :date, presence: true
      after_commit :set_business_status

      private
      def set_business_status
        business.closed!
      end
    end
  end
end

app/models/businesses/business_requirement.rb
module Businesses
  class BusinessRequirement < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    belongs_to :required_document, class_name: "BploSection::Settings::RequiredDocument"
    belongs_to :business
    has_many :verifications, class_name: "Businesses::BusinessRequirements::Verification", dependent: :destroy
    has_many :issuances, class_name: "Businesses::BusinessRequirements::Issuance", dependent: :destroy

    delegate :name, :default_requirement?, to: :required_document, allow_nil: true
    delegate :department_name, to: :required_document
    def self.verified
      all.select{ |a| a.verified? }
    end
    def self.not_verified
      all.select{ |a| !a.verified? }
    end
    def department
      required_document.department
    end
    def verified?
      has_current_verification? || has_current_issuance?
    end

    def has_current_verification?
      verifications.present? && verifications.last.submission_date && verifications.last.submission_date.between?(Time.zone.now.beginning_of_year, Time.zone.now.end_of_year)
    end
    def has_current_issuance?
      issuances.present?  && issuances.last.issue_date && issuances.last.issue_date.between?(Time.zone.now.beginning_of_year, Time.zone.now.end_of_year)
    end
  end
end

app/models/businesses/business_requirements/issuance.rb
module Businesses
  module BusinessRequirements
    class Issuance < ApplicationRecord
      belongs_to :business_requirement, class_name: "Businesses::BusinessRequirement"
      validates :reference_number, :issue_date, presence: true
      delegate :department, to: :business_requirement
    end
  end
end

app/models/businesses/business_tin_plate.rb
module Businesses
  class BusinessTinPlate < ApplicationRecord
    belongs_to :business
    belongs_to :business_permit_approval, class_name: "Businesses::BusinessPermitApproval"
  end
end

app/models/businesses/rent.rb
module Businesses
  class Rent < ApplicationRecord
    belongs_to :business
  end
end

app/views/businesses/_index.html.erb
          <%=form_tag businesses_path, method: :get, class: "search-form" do %>
            <div class="input-group">
              <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Business ..", id: 'taxpayer-search-form' %>
              <span class="input-group-btn">
                <%= button_tag(type: 'submit', id: "search-btn", class: "btn btn-flat") do %>
                  <i class="fa fa-search"></i>
                <% end %>
              </span>
            </div>
          <% end %>

<br>
       <% if businesses.present? %>
          <% businesses.each do |business| %>
            <%=link_to business_path(business) do %>
              <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-3">
                  <%=image_tag(business.avatar.url(:large), height: 120, width: 120, class: "img-responsive img-square") %>
                </div>
                <div class="col-md-4 col-sm-4 col-xs-9">
                  <span class="text-blue"><b><%=business.name.try(:upcase) %></b></span><br>
                  <small class="text-muted"><i class="fa fa-map-marker"></i> &nbsp; <%=business.full_address %></small><br>
                  <small class="text-muted"><i class="fa fa-phone"></i> &nbsp; <%#=taxpayer.contact_number %></small><br><br>
                  <p><span class="label bg-<%=business.status_color %>"><%=business.business_status %></span></p>

                </div>
                <div class="col-md-4 col-md-offset-2 hidden-xs">
                  <% if business.assessed_for_current_year? %>
                 <br>
                 <br>
                 <span class="text-muted"> <%= number_to_currency business.balance %></span><br>
                 <small class="text-muted"> BALANCE </small>
                 <% end %>
                </div>

              </div>
              <hr>
            <% end %>
          <% end %>
          <% if businesses.present? %>
          <center><%= paginate businesses %> </center>
          <% end %>
        <% else %>
          No businesses found.
        <% end %>

app/views/businesses/_show.html.erb
<% breadcrumb :business, @business %>
<div class="row">
  <div class="col-md-12">
    <div class="box box-widget widget-user-2">
      <!-- Add the bg color to the header using any of the bg-* classes -->
      <div class="widget-user-header">
        <div class="widget-user-image">
        <%=image_tag(@business.avatar.url(:large), class: "img-square") %>
        </div>
        <!-- /.widget-user-image -->
        <h3 class="widget-user-username"><%= @business.name.upcase %></h3>
        <% @business.taxpayers.distinct.each do |taxpayer| %>
          <h5 class="widget-user-desc">&nbsp; &nbsp; &nbsp; &nbsp; <%=image_tag(taxpayer.avatar.url(:small), height: 35, width: 35, class: "img-circle") %> &nbsp; &nbsp; <%=taxpayer.full_name %></h5>
        <% end %>

      </div>
    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
         <li class="<%= 'active' if current_page?(business_path(@business))%>"><%= link_to 'Checklist', business_path(@business) %></li>
         <li class="<%= 'active' if current_page?(business_info_index_path(@business))%>"><%= link_to 'Info', business_info_index_path(@business) %></li>
         <li class="<%= 'active' if current_page?(business_assessments_path(@business))%>"><%= link_to 'Assessments/Payments', business_assessments_path(@business) %></li>
         <% if current_user.bplo_officer? || current_user.mayors_office_staff? %>
           <li class="<%= 'active' if current_page?(business_business_permits_path(@business))%>"><%= link_to 'Permits', business_business_permits_path(@business) %></li>
         <% end %>
        <% if current_user.bplo_officer? || current_user.system_administrator? %>
           <li class="<%= 'active' if current_page?(business_settings_path(@business))%>"><%= link_to 'Settings', business_settings_path(@business) %></li>
        <% end %>
      </ul>
      <div class="tab-content box-body">
        <% if current_page? business_path(@business) %>
          <%=render 'businesses/partials/checklist' %>
        <% end %>
        <% if current_page? business_info_index_path(@business) %>
          <%= render 'businesses/partials/business_info' %>
        <% end %>

        <% if current_page? business_assessments_path(@business) %>
          <%=render 'businesses/partials/payments' %>
        <% end %>
        <% if current_page? business_business_permits_path(@business) %>
          <%=render 'businesses/partials/permits' %>
        <% end %>
        <% if current_page? business_settings_path(@business) %>
          <%=render 'businesses/partials/settings' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/businesses/index.html.erb
<% breadcrumb :businesses %>
<div class="row">
  <div class="col-md-8">
    <div class="box box-default">
    <div class="box-header with-border">
      <div class="row">
        <div class="col-md-2 hidden-xs">
          <h3 class="box-title"> Businesses </h3>
        </div>
        <div class="col-md-7 col-xs-12">
          <%=form_tag businesses_path, method: :get, class: "search-form" do %>
            <div class="input-group">
              <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search ..", id: 'taxpayer-search-form' %>
              <span class="input-group-btn">
                <%= button_tag(type: 'submit', id: "search-btn", class: "btn btn-flat") do %>
                  <i class="fa fa-search"></i>
                <% end %>
              </span>
            </div>
          <% end %>
        </div>
        <div class="col-md-2">
          <% if policy([Business.new]).new? %>
            <%= link_to 'New Application', new_business_registration_path, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>

      <div class="box-body">
       <% if @businesses.present? %>
          <% @businesses.each do |business| %>
            <%=link_to business_path(business) do %>
              <div class="row">
                <div class="col-md-2 col-sm-2 col-xs-3">
                  <%=image_tag(business.avatar.url(:large), height: 120, width: 120, class: "img-responsive img-square") %>
                </div>
                <div class="col-md-8 col-sm-4 col-xs-9">
                  <span class="text-blue"><b><%=business.name.try(:upcase) %></b></span><br>
                  <small class="text-muted"><i class="fa fa-map-marker"></i> &nbsp; <%=business.full_address %></small><br>
                  <small class="text-muted"><i class="fa fa-phone"></i> &nbsp; <%#=taxpayer.contact_number %></small><br><br>
                </div>


              </div>
              <hr>
            <% end %>
          <% end %>
          <center><%= paginate @businesses %> </center>
        <% else %>
          No businesses found.
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="box box-default">
      <div class="row">
        <div class="col-md-12">
          <h2><center><%= Business.count %></center></h2>
          <center><small> TOTAL BUSINESSES </small>
        </div>
      </div>
      <br>
    </div>
    <div class="box box-default">
      <div class="box-header">
        <h3 class="box-title"> Businesses per Barangay </h3>
      </div>
      <div class="box-body">
        <% Addresses::Barangay.in_lamut.each do |barangay| %>
          <%=link_to monitoring_barangay_path(barangay) do %>
            <div class="row">
              <div class="col-md-8">
                <%=barangay.name %>
              </div>
              <div class="col-md-4">
                <span class="pull-right">
                  <span class="badge bg-gray"><%= barangay.businesses.uniq.count %></span>
                </span>
              </div>
            </div>
          <% end %>
          <hr>
        <% end %>
      </div>
    </div>
</div>

app/views/businesses/show.html.erb
<% breadcrumb :business, @business %>
<%= render 'show' %>