config/routes.rb
Rails.application.routes.draw do

  unauthenticated :user do
    root :to => 'home#index', :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  end
  root :to => 'fire_department#index', :constraints => lambda { |request| request.env['warden'].user.role == 'fire_safety_officer' if request.env['warden'].user }, as: :fire_department_root
   root :to => 'treasury_department#index', :constraints => lambda { |request| request.env['warden'].user.role == 'collection_officer' if request.env['warden'].user }, as: :treasury_department_root
resources :search_results, only: [:index]
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'bplo_officer' if request.env['warden'].user }, as: :bplo_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'engineering_officer' if request.env['warden'].user }, as: :engineering_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'zoning_officer' if request.env['warden'].user }, as: :zoning_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'system_administrator' if request.env['warden'].user }, as: :admin_department_root
root :to => 'businesses#index', :constraints => lambda { |request| request.env['warden'].user.role == 'mayors_office_staff' if request.env['warden'].user }, as: :mayor_department_root

  devise_for :users, controllers: { sessions: 'users/sessions' , registrations: "bplo_section/settings/users"}
  resources :users, only: [:show, :edit, :update]
  resources :reports, only: [:index]
  namespace :reports do
    resources :bir, only: [:index]
    resources :gcf, only: [:index]
    resources :dilg, only: [:index]
    resources :cmci, only: [:index]
    resources :dti, only: [:index]
    resources :bfp, only: [:index]
    resources :philhealth, only: [:index]
    resources :sss, only: [:index]
  end

  resources :competetive_index_categories, only: [:show]
  resources :collections, only: [:index, :show, :destroy]
  resources :business_requirement_verifications, only: [:create]
  resources :business_permits, only: [:index, :show]
  resources :business_activities, only: [:destroy], module: :businesses
  resources :business_fees, only: [:destroy], module: :businesses
  resources :dashboard, only: [:index]
  resources :taxpayers do
    resources :taxpayer_businesses, only: [:new, :create], module: :taxpayers
  end
  resources :businesses, only: [:index, :show, :destroy] do
    resources :info, only: [:index], module: :businesses
    resources :checklist, only: [:index], module: :businesses
    resources :settings, only: [:index], module: :businesses
    resources :business_permits, only: [:index], module: :businesses
    resources :bir_registrations, only: [:new, :create], module: :businesses
    resources :dti_registrations, only: [:new, :create], module: :businesses
    resources :sec_registrations, only: [:new, :create], module: :businesses
    resources :cda_registrations, only: [:new, :create], module: :businesses

    resources :business_tax_payments, only: [:new, :create], module: :businesses
    resources :payments, only: [:new, :create], module: :businesses

    resources :assessments, only: [:index, :new, :create], module: :businesses
    resources :additional_assessments, only: [:new, :create], module: :businesses
    resources :revocations, only: [:new, :create], module: :businesses
    resources :late_registration_interests, only: [:create], module: :businesses
    resources :fire_safety_inspection_fee_collections, only: [:new, :create], module: :businesses

  end
  resources :departments, only: [:index, :new, :create]
  resources :business_registrations, only: [:new, :create]
  resources :business_permit_applications, shallow: true do
    resources :permit_approvals, only: [:new, :create]
  end

  namespace :bplo_section do
    resources :line_of_businesses, only: [:show]
    resources :taxpayers, only: [:show] do
      resources :businesses, only: [:new, :create]
      resources :tricycles, only: [:new, :create]
    end

    resources :businesses, only: [:show, :edit, :update] do
      resources :line_of_business_selections, only: [:new, :create], module: :businesses
      resources :business_permit_applications, only: [:new, :create], module: :businesses
      resources :business_activities, only: [:index, :new, :create]
      resources :cockpit_details, only: [:index, :new, :create]
      resources :gross_sales, only: [:new, :create, :edit, :update], module: :businesses
      resources :business_requirements, only: [:new, :create]
      resources :business_fees, only: [:new, :create]
      resources :gross_sales_tax_configs, only: [:edit, :update], module: :configurations
      resources :building_permit_fees, only: [:new, :create], module: :businesses
      resources :electrical_installation_fees, only: [:new, :create], module: :businesses
      resources :plumbing_installation_fees, only: [:new, :create], module: :businesses
      resources :other_accessories_fees, only: [:new, :create], module: :businesses
      resources :engineering_penalties, only: [:new, :create], module: :businesses
      resources :surcharges, only: [:new, :create], module: :businesses
      resources :late_registration_interests, only: [:new, :create], module: :businesses


      resources :zoning_fees, only: [:new, :create], module: :businesses
      resources :annual_inspection_fees, only: [:new, :create], module: :businesses
      resources :occupancy_permit_fees, only: [:new, :create], module: :businesses
      resources :documentary_stamp_fees, only: [:new, :create, :edit], module: :businesses
      resources :sealing_fees, only: [:new, :create], module: :businesses
      resources :stalls, only: [:new, :create], module: :businesses

    end
    resources :business_activities, only: [:show] do
      resources :gross_sales, only: [:new, :create]
    end



    resources :gross_sales_tax_business_categories, only: [:show] do
      resources :gross_sales_taxes, only: [:new, :create], module: :taxes
    end
    resources :business_requirements, only: [:destroy]


    namespace :configs do
      resources :fire_safety_inspection_fee_configs, only: [:new, :create]
    end

    namespace :taxes do
      resources :capital_taxes, only: [:new, :create]
    end
    resources :settings, only: [:index]
    namespace :settings do
      resources :public_markets, only: [:new, :create]
      resources :ownership_types, only: [:new, :create, :edit, :update]
      resources :mode_of_payments, only: [:new, :create, :edit, :update]
      resources :barangays, only: [:new, :create, :edit, :update]
      resources :line_of_businesses, only: [:index, :new, :create, :edit, :update, :show]
      resources :fees, only: [:new, :create, :edit, :update]
      resources :taxes, only: [:new, :create, :edit, :update]
      resources :cockpit_personnel_fees, only: [:new, :create, :edit, :update]

      resources :late_payment_surcharges, only: [:new, :create]
      resources :interest_rates, only: [:new, :create]
      resources :required_documents, only: [:new, :create, :edit, :update]
      resources :departments, only: [:new, :create]
      resources :gross_sales_tax_business_categories, only: [:new, :create]
      resources :users, only: [:new, :create, :show]
      resources :signatories, only: [:new, :create]
      resources :permit_application_date_ranges, only: [:new, :create]
      resources :tricycle_fees, only: [:new, :create, :edit, :update]
      resources :tricycle_requirements, only: [:new, :create, :edit, :update]
      resources :tricycle_organizations, only: [:new, :create, :edit, :update]
    end
  end
  resources :business_requirements, shallow: true do
    resources :verifications, only: [:new, :create], module: [:businesses, :business_requirements]
    resources :issuances, only: [:new, :create], module: [:businesses, :business_requirements]
  end
  namespace :fees_settings do
    resources :sanitary_inspection_fees, only: [:new, :create]
    resources :storage_permit_fees, only: [:new, :create]
  end
  resources :monitoring, only: [:index]
  namespace :monitoring do
    resources :closed_businesses, only: [:index]

    resources :unrenewed_businesses, only: [:index]
    resources :barangays, only: [:show] do
      match "/registered_businesses" => "registered_businesses#index",  via: [:get], on: :collection
      match "/unrenewed_businesses" => "unrenewed_businesses#index",  via: [:get], on: :collection
    end
  end
  resources :bir_registrations, only: [:edit, :update], module: :registrations
  resources :dti_registrations, only: [:edit, :update], module: :registrations
  resources :sec_registrations, only: [:edit, :update], module: :registrations
  resources :cda_registrations, only: [:edit, :update], module: :registrations
  namespace :public_markets do
    resources :transient_tenants, only: [:index]
    resources :regular_tenants, only: [:index]
  end
  resources :tricycles do
    resources :applicable_tricycle_fees, only: [:new, :create], module: :tricycles
    resources :fare_adjustment_fees, only: [:new, :create], module: :tricycles
    resources :late_registration_interests, only: [:new, :create], module: :tricycles
    resources :surcharges, only: [:new, :create], module: :tricycles
    resources :tricycle_requirements, only: [:new, :create]
    resources :assessments, only: [:new, :create], module: :tricycles
    resources :payments, only: [:new, :create], module: :tricycles
    resources :tricycle_permit_applications, only: [:new, :create], module: :tricycles
  end

  resources :applicable_tricycle_fees, only: [:destroy], module: :tricycles
  resources :tricycle_registrations, only: [:new, :create]
  resources :tricycle_permit_applications, shallow: true do

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @entries = Accounting::Entry.payment.includes(:debit_amounts, :credit_amounts, :commercial_document).page(params[:page]).per(30)
  end
  def show
    @entry = Accounting::Entry.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Accounting::EntryPdf.new(@entry, view_context)
          send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Assessment.pdf"
      end
    end
  end
  def destroy
    @entry = Accounting::Entry.find(params[:id])
    @entry.destroy
    redirect_to business_url(@entry.commercial_document), notice: "Assessment deleted successfully."
  end
end

app/controllers/fire_department/collections_controller.rb
module FireDepartment
  class CollectionsController < ApplicationController
    def index
      if params[:search].present?
        @collections = FireDeptCollection.text_search(params[:search]).page(params[:page]).per(30)
      else
        @collections = FireDeptCollection.all.order(entry_date: :desc).page(params[:page]).per(30)
      end
    end
    def show
      @collection = FireDeptCollection.find(params[:id])
    end
    def edit
      @collection = FireDeptCollection.find(params[:id])
    end
    def update
      @collection = FireDeptCollection.find(params[:id])
      @collection.update(collection_params)
      if @collection.save
        redirect_to fire_department_collection_url(@collection), notice: "Updated successfully."
      else
        render :edit
      end
    end

    private
    def collection_params
      params.require(:fire_dept_collection).permit(:entry_date, :reference_number)
    end
  end
end

app/controllers/treasury_department/assessments/payments_controller.rb
module TreasuryDepartment
  module Assessments
    class PaymentsController < ApplicationController
      def new
        @assessment = Accounting::Entry.find(params[:assessment_id])
        @entry = Accounting::Entry.new
        @entry.credit_amounts.build
        @entry.debit_amounts.build
      end
      def create
        @assessment = Accounting::Entry.find(params[:assessment_id])
        @entry = Accounting::Entry.create(entry_params)
        @entry.commercial_document = @assessment.commercial_document
        @entry.recorder = current_user
        @entry.transaction_type = 'payment'
        @entry.barangay = @assessment.commercial_document.barangay
        @entry.description = "Payment of fees and taxes"
        if @entry.save!
          redirect_to treasury_department_business_path(@assessment.commercial_document), notice: 'Payment saved successfully.'
            @assessment.paid!
        else
          render :new
        end
      end

      private def entry_params
        params.require(:accounting_entry).permit(:reference_number, :description, :entry_date, credit_amounts_attributes: [:amount, :account_id, :id], debit_amounts_attributes: [:amount, :account_id, :id] )
      end
    end
    end
end

app/controllers/treasury_department/barangays_controller.rb
module TreasuryDepartment
  class BarangaysController < ApplicationController
    def index
      @barangays = Addresses::Barangay.in_lamut
    end

    def show
      @barangay = Addresses::Barangay.find(params[:id])
      @businesses = @barangay.businesses.page(params[:page]).per(50)
      @from_date = params[:from_date] ? Time.parse(params[:from_date]) : Time.now.beginning_of_year.beginning_of_day
      @to_date = params[:to_date] ? Time.parse(params[:to_date]) : Time.now.end_of_year.end_of_day
    end
  end
end

app/controllers/treasury_department/businesses_controller.rb
module TreasuryDepartment
  class BusinessesController < ApplicationController
    def index
      if params[:search].present?
        @businesses = Business.text_search(params[:search]).page(params[:page]).per(30)
      else
        @businesses = Business.all.order(:name).page(params[:page]).per(50)
      end
    end
    def show
      @business = Business.friendly.find(params[:id])
    end
  end
end

app/controllers/treasury_department/collections_controller.rb
module TreasuryDepartment
  class CollectionsController < ApplicationController
    def index
      if params[:search].present?
        @collections = Accounting::Entry.text_search(params[:search]).page(params[:page]).per(30)
      else
        @collections = Accounting::Entry.payment.all.order(entry_date: :desc).page(params[:page]).per(30)
      end
    end
    def show
      @collection = Accounting::Entry.find(params[:id])
      respond_to do |format|
        format.html
        format.pdf do
          pdf = Accounting::PaymentPdf.new(@collection, view_context)
            send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Assessment.pdf"
        end
      end
    end
    def edit
      @collection = Accounting::Entry.find(params[:id])
    end
    def update
      @collection = Accounting::Entry.find(params[:id])
      @collection.update(collection_params)
      if @collection.save
        redirect_to treasury_department_collection_url(@collection), notice: "OR Number Updated successfully."
      else
        render :edit
      end
    end

    private
    def collection_params
      params.require(:accounting_entry).permit(:reference_number, :description, :entry_date, credit_amounts_attributes: [:amount, :account_id, :id], debit_amounts_attributes: [:amount, :account_id, :id] )
    end
  end
end

app/controllers/treasury_department_controller.rb
class TreasuryDepartmentController < ApplicationController
  def index
  end
end 

app/views/treasury_department/collections/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <!-- Widget: user widget style 1 -->
  <div class="box box-widget widget-user-2">
    <!-- Add the bg color to the header using any of the bg-* classes -->
    <div class="widget-user-header">
      <div class="widget-user-image">
        <%=image_tag(@collection.recorder.avatar.url(:large), class: "img-circle") %>
      </div>
      <!-- /.widget-user-image -->
      <h3 class="widget-user-username"><%= @collection.recorder.try(:full_name).try(:upcase) %></h3>
      <br>
      <hr>
        <%=simple_form_for @collection, url: :treasury_department_collection do |f| %>
        <%= f.error_notification %>
          <%= f.input :reference_number, label: "OR Number" %>
          <%= f.input :entry_date, label: "Date", as: :string, input_html: { class: "datepicker" } %>

          <%= f.submit "Update", class: "btn btn-primary btn-flat", data: {disable_with: "Updating..."} %>
        <% end %>
        <hr>
          <h5 class="widget-user-desc text-muted"><i class="fa fa-bookmark"></i> OR Number <%= @collection.reference_number %></h5>
          <h5 class="widget-user-desc text-muted"><i class="fa fa-calendar"></i> Date <%= @collection.entry_date.strftime("%B %e, %Y") %></h5>

    </div>
    <div class="box-body">
<% @collection.credit_amounts.order(amount: :asc).each do |amount| %>
  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-8">
      <%= amount.account.name.gsub("Accounts Receivable - ", "").singularize %>
    </div>
    <div class="col-md-2">
      <span class="pull-right"> <%= number_to_currency amount.amount %></span>
    </div>
  </div>
  <br>
<% end %>
<hr>
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-8">
    <b>TOTAL</b>
  </div>
  <div class="col-md-2">
    <span class="pull-right"><b><%= number_to_currency @collection.credit_amounts.sum(:amount) %></b></span>
  </div>
</div>
<br>

app/views/treasury_department/collections/index.html.erb
<% breadcrumb :treasury_department_collections %>
<div class="row">
  <div class="col-md-7">
    <div class="box box-default">
    <div class="box-header with-border">
      <div class="row">
        <div class="col-md-12 col-xs-12">
          <%=form_tag treasury_department_collections_path, method: :get, class: "search-form" do %>
            <div class="input-group">
              <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Enter OR Number...", id: 'taxpayer-search-form' %>
              <span class="input-group-btn">
                <%= button_tag(type: 'submit', id: "search-btn", class: "btn btn-flat") do %>
                  <i class="fa fa-search"></i>
                <% end %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
      <div class="box-body">
        <div class="table table-responsive">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th> </th>
                <th> Date </th>
                <th> OR Number </th>
                <th> Taxpayer </th>
                <th> Amount </th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @collections.order(created_at: :desc).each do |collection| %>
                <tr>
                  <td><%= image_tag(collection.recorder.avatar.url(:medium), class: "img-circle", height: 45, width: 45) %> </td>
                  <td> <%=link_to collection.entry_date.strftime("%B %e, %Y"), treasury_department_collection_path(collection) %><br>
                  </td>
                  <td> <%= link_to collection.reference_number, treasury_department_collection_path(collection) %></td>
                  <td> <%=collection.commercial_document.try(:taxpayers_full_name) %></td>
                  <td> <span class="pull-right"> <%=number_to_currency collection.credit_amounts.sum(:amount) %> </span></td>
                  <td>
                    <%=link_to treasury_department_collection_path(collection, format: "pdf") do  %>
                      <span class="btn btn-default bg-gray btn-xs" title="Print(PDF)" data-toggle="tooltip"><i class="fa fa-print"></i></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
            <center><%= paginate @collections %> </center>
        </div>
    </div>
  </div>
</div>
  <div class="col-md-5">
    <div class="box box-solid">
      <div class="box-header">
        <h3 class="box-title"> Collections </h3>
      </div>
      <div class="box-body">
        <% Accounting::Account.accounts_receivables.sort_by(&:debits_balance).reverse.each do |account| %>
          <div class="row">
            <div class="col-md-7 col-md-offset-1">
              <%= account.name.gsub('Accounts Receivable - ', '') %>
            </div>
            <div class="col-md-3">
              <span class="pull-right">
                <%= number_to_currency account.credits_balance(from_date: @from_date, to_date: @to_date) %>
              </span>
            </div>
          </div>
          <br>
        <% end %>

app/views/treasury_department/collections/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <!-- Widget: user widget style 1 -->
  <div class="box box-solid">
    <div class="box-header">
    </div>
    <div class="box-body">
      <p class="text-muted">Collection Details </p>
      <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-5">
          Collector
        </div>
        <div class="col-md-6">
          <%=image_tag(@collection.recorder.avatar.url(:large), class: "img-circle", height: 35, width: 35) %> &nbsp; &nbsp;
          <%= @collection.recorder.try(:full_name) %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-5">
          OR Number
        </div>
        <div class="col-md-6">
          <%= @collection.reference_number %>
           <% if current_user == @collection.recorder %>
              <span class="pull-right"> <%=link_to edit_treasury_department_collection_path(@collection) do %>
                <span class="btn btn-warning btn-xs"><i class="fa fa-pencil"></i> Edit </span>
                <% end %>
                
              </span>
            <% end %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-5">
          Date Collected
        </div>
        <div class="col-md-6">
          <%= @collection.entry_date.strftime("%B %e, %Y") %>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-5">
          Taxpayer
        </div>
        <div class="col-md-6">
          <%= @collection.commercial_document.try(:taxpayer_full_name) %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-5">
          Contact Number
        </div>
        <div class="col-md-6">
          <%= @collection.commercial_document.try(:taxpayer_contact_number) %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-5">
          Address
        </div>
        <div class="col-md-6">
          <%= @collection.commercial_document.try(:taxpayer_full_address) %>
        </div>
      </div>
      <hr>

<% @collection.credit_amounts.order(amount: :asc).each do |amount| %>
  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-8">
      <%= amount.account.name.gsub("Accounts Receivable - ", "").singularize %>
    </div>
    <div class="col-md-2">
      <span class="pull-right"> <%= number_to_currency amount.amount %></span>
    </div>
  </div>
  <br>
<% end %>
<hr>
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="col-md-8">
    <b>TOTAL</b>
  </div>
  <div class="col-md-2">
    <span class="pull-right"><b><%= number_to_currency @collection.credit_amounts.sum(:amount) %></b></span>
  </div>
</div>
<br>